DROP TABLE IF EXISTS `course` CASCADE;

CREATE TABLE `course`
(
    `course_id`           bigint generated by default as identity,
    `year`                int NULL,
    `semester`            int NULL,
    `grades`              varchar(255) NULL,
    `curriculum`          varchar(255) NULL,
    `course_area`         varchar(255) NULL,
    `base_code`           varchar(255) NULL,
    `div_code`            varchar(255) NULL,
    `course_name`         varchar(255) NULL,
    `professor`           varchar(255) NULL,
    `campus`              varchar(255) NULL,
    `schedules`           varchar(1000) NULL,
    `credit`              int NULL,
    `theory`              int NULL,
    `practice`            int NULL,
    `lecture_type`        varchar(255) NULL,
    `lecture_category`    varchar(255) NULL,
    `lecture_language`    varchar(255) NULL,
    `requirement_type`    varchar(255) NULL,
    `offering_college`    varchar(255) NULL,
    `offering_department` varchar(255) NULL,
    `remarks`             varchar(255) NULL
);

ALTER TABLE `course`
    ADD CONSTRAINT `PK_COURSE` PRIMARY KEY (
                                            `course_id`
        );
